---
name: Tests
on: [ push, pull_request ]
jobs:
  test:
    name: Test (Ruby ${{ matrix.ruby }}, Rails ${{ matrix.rails }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { ruby: '3.2', rails: '7.0.4.2' }
          - { ruby: '3.2', rails: '6.1.7.2' }
          - { ruby: '3.1', rails: '7.0.4.2' }
          - { ruby: '3.1', rails: '6.1.7.2' }
          - { ruby: '3.1', rails: '6.0.6.1' }
          - { ruby: '3.0', rails: '6.1.7.2' }
          - { ruby: '3.0', rails: '6.0.6.1' }
          - { ruby: '2.7', rails: '6.1.7.2' }
          - { ruby: '2.7', rails: '6.0.6.1' }
          - { ruby: '2.7', rails: '5.2.8.1' }
          - { ruby: '2.6', rails: '5.2.8.1' }
          - { ruby: '2.5', rails: '5.2.8.1' }
          - { ruby: '2.4', rails: '5.1.7' }
          - { ruby: '2.3', rails: '5.0.7.2' }
          - { ruby: '2.2', rails: '4.2.11.3' }
    env:
      RAILS_VERSION: ${{ matrix.rails }}
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake
